stages:
  - build
  - deploy

build_3.7_alpine:
  image: python:3.7-alpine
  stage: build
  before_script:
    - apk add --no-cache --update python3-dev gcc build-base
    - pip3.7 install -r devreq.txt -U
  script:
    - PYTHONPATH="$(pwd)" pytest -vs --cov=async_pokepy --cov-report term-missing:skip-covered
    - flake8 .
    - pylint -j "$(nproc)" async_pokepy
    - isort . --check-only --recursive
    - python3.7 setup.py sdist bdist_egg bdist_wheel
    - rm -rf async_pokepy
    - find dist -name *.whl -exec pip3.7 install '{}' +
    - pytest -vs
    - cd docs && make html
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

build_3.6_alpine:
  image: python:3.6-alpine
  stage: build
  before_script:
    - apk add --no-cache --update python3-dev gcc build-base
    - pip3.6 install -r devreq.txt -U
  script:
    - PYTHONPATH="$(pwd)" pytest -vs --cov=async_pokepy --cov-report term-missing:skip-covered
    - flake8 .
    - pylint -j "$(nproc)" async_pokepy
    - isort . --check-only --recursive
    - python3.6 setup.py sdist bdist_egg bdist_wheel
    - rm -rf async_pokepy
    - find dist -name *.whl -exec pip3.6 install '{}' +
    - pytest -vs
    - cd docs && make html
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

build_3.5_alpine:
  image: python:3.5-alpine
  stage: build
  before_script:
    - apk add --no-cache --update python3-dev gcc build-base
    - pip3.5 install -r devreq.txt -U
  script:
    - PYTHONPATH="$(pwd)" pytest -vs --cov=async_pokepy --cov-report term-missing:skip-covered
    - flake8 .
    - pylint -j "$(nproc)" async_pokepy
    - isort . --check-only --recursive
    - python3.5 setup.py sdist bdist_egg bdist_wheel
    - rm -rf async_pokepy
    - find dist -name *.whl -exec pip3.5 install '{}' +
    - pytest -vs
    - cd docs && make html
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

build_3.7_stretch:
  image: python:3.7-stretch
  stage: build
  before_script:
    - pip3.7 install -r devreq.txt -U
  script:
    - PYTHONPATH="$(pwd)" pytest -vs --cov=async_pokepy --cov-report term-missing:skip-covered
    - flake8 .
    - pylint -j "$(nproc)" async_pokepy
    - isort . --check-only --recursive
    - python3.7 setup.py sdist bdist_egg bdist_wheel
    - rm -rf async_pokepy
    - find dist -name *.whl -exec pip3.7 install '{}' +
    - pytest -vs
    - cd docs && make html
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

build_3.6_stretch:
  image: python:3.6-stretch
  stage: build
  before_script:
    - pip3.6 install -r devreq.txt -U
  script:
    - PYTHONPATH="$(pwd)" pytest -vs --cov=async_pokepy --cov-report term-missing:skip-covered
    - flake8 .
    - pylint -j "$(nproc)" async_pokepy
    - isort . --check-only --recursive
    - python3.6 setup.py sdist bdist_egg bdist_wheel
    - rm -rf async_pokepy
    - find dist -name *.whl -exec pip3.6 install '{}' +
    - pytest -vs
    - cd docs && make html
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

build_3.5_stretch:
  image: python:3.5-stretch
  stage: build
  before_script:
    - pip3.5 install -r devreq.txt -U
  script:
    - PYTHONPATH="$(pwd)" pytest -vs --cov=async_pokepy --cov-report term-missing:skip-covered
    - flake8 .
    - pylint -j "$(nproc)" async_pokepy
    - isort . --check-only --recursive
    - python3.5 setup.py sdist bdist_egg bdist_wheel
    - rm -rf async_pokepy
    - find dist -name *.whl -exec pip3.5 install '{}' +
    - pytest -vs
    - cd docs && make html
  artifacts:
    paths:
      - dist
      - docs/_build
    expire_in: 2 days
  retry: 1
  when: always

deploy:
  stage: deploy
  image: python:3.7-alpine
  before_script:
    - pip3.7 install -U twine
    - ls dist
    - export TWINE_USERNAME="$(echo -e $TWINE_USERNAME)"
    - export TWINE_PASSWORD="$(echo -e $TWINE_PASSWORD)"
  script:
    - twine upload dist/*
  artifacts:
    paths:
      - dist
  only:
    - tags@PendragonLore/async_pokepy
