stages:
  - build
  - deploy

before_script:
  - apk add --no-cache --update python3-dev  gcc build-base
  - pip3.7 install -r devreq.txt

poke_build:
  image: python:3.7-alpine
  stage: build
  script:
    - PYTHONPATH="$(pwd)" pytest -vs --cov=async_pokepy --cov-report term-missing:skip-covered
    - flake8 .
    - pylint -j "$(nproc)" async_pokepy
    - python3.7 setup.py sdist bdist_egg bdist_wheel
    - rm -rf async_pokepy
    - pytest -vs
    - cd docs && make html
  retry: 1
  when: always

deploy:
  stage: deploy
  before_script:
    - pip install -U twine
    - ls dist
    - export TWINE_USERNAME="$(echo -e $TWINE_USERNAME)"
    - export TWINE_PASSWORD="$(echo -e $TWINE_PASSWORD)"
  script:
    - twine upload dist/*
  artifacts:
    paths:
      - dist
  only:
    - master
